[tool.black]
exclude = "/(.git|.direnv|.mypy_cache|deps)/"

[tool.mypy]
disallow_untyped_defs = true
ignore_missing_imports = true
exclude = '''(?x)(
    ^deps/$
)'''

[tool.pytest.ini_options]
testpaths = ["tests/unit"]
