---
name: CI

on: [push, pull_request]

jobs:
  lint:
    name: "Lint checks"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-python@v2"
        with:
          python-version: "3.8"

      - name: "Install dependencies"
        run: |
          set -xe
          pip install --upgrade pip wheel
          pip install -r requirements/lint.txt

      - name: "Run linting checks"
        run: |
          black --check .
          flake8
          mypy .

  tests:
    name: "Unit tests"
    runs-on: "ubuntu-latest"
    needs: lint

    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-python@v2"
        with:
          python-version: "3.8"

      - name: "Install dependencies"
        run: |
          set -xe
          python -vv
          pip install --upgrade pip wheel
          pip install -r requirements/test.txt

      - name: "Run tests"
        run: |
          coverage run -m pytest
          coverage report --fail-under=100

  integration-tests:
    name: "Integration tests"
    needs: tests

    strategy:
      fail-fast: false
      matrix:
        st-version: [4]
        os: ["ubuntu-latest", "macOS-latest", "windows-latest"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: SublimeText/UnitTesting/actions/setup@v1
        with:
          sublime-text-version: ${{ matrix.st-version }}
      - uses: SublimeText/UnitTesting/actions/run-tests@v1
        with:
          coverage: false
          codecov-upload: false
